name: lint

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'AUTHORS'

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        # remember to sync the ruff-check version number with pyproject.toml
      - name: Run ruff check
        uses: astral-sh/ruff-action@84f83ecf9e1e15d26b7984c7ec9cf73d39ffc946 # v3.3.1
        with:
          version: 0.11.5

        # remember to sync the ruff-check version number with pyproject.toml
      - name: Run ruff format
        uses: astral-sh/ruff-action@84f83ecf9e1e15d26b7984c7ec9cf73d39ffc946 # v3.3.1
        with:
          version: 0.11.5
          args: 'format --check'
